name: RUN SuperTest API Test CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  RUN-SuperTest-API-Test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Installation of related packages
      run: |
            cd mock_user_authentication_API
            npm ci
            cd ..
            cd Testing_supertest
            npm ci
            cd ..

    - name: RUN mock-user-auth
      run: |
            cd mock_user_authentication_API
            npm run dev 8081
      
    - name: RUN SuperTest API Testing
      run: |
            cd ..
            cd Testing_supertest
            npm run test
      
    # - name: Archive SuperTest mochawesome test report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: SuperTest-mochawesome-test-report
    #     path: Report

    # - name: Upload SuperTest mochawesome report to GitHub
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: SuperTest-mochawesome-test-report
    #     path: Report
