name: RUN SuperTest API Test CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    

jobs:
  Run_mock_user_authentication_API:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'mock_user_authentication_API/package-lock.json'
        
    - name: Installation of related packages
      run: |
            cd mock_user_authentication_API
            npm i --save mock-user-auth
            npm ci
            cd ..
            

    - name: RUN mock-user-auth
      run: |
            cd mock_user_authentication_API
            npm run dev 8081
  
  Test_mock_user_authentication_API_By_supertest:
    needs: Run_mock_user_authentication_API
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'Testing_supertest/package-lock.json'
        
    - name: Installation of related packages
      run: |
            cd Testing_supertest
            npm i --save supertest mocha chai@4.2.0 mochawesome
            npm ci
            cd ..
            

    - name: RUN SuperTest API Testing
      run: |
            cd Testing_supertest
            npm run test
      

      
    # - name: Archive SuperTest mochawesome test report
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: SuperTest-mochawesome-test-report
    #     path: Report

    # - name: Upload SuperTest mochawesome report to GitHub
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: SuperTest-mochawesome-test-report
    #     path: Report
